channels:
  - conda-forge
dependencies:
  - python=3.7
  - pathlib
  - typing
  - isort  # only required for auto-format code
  - black  # only required for auto-format code
  - pytest  # only required for running tests
  - pytest-cov  # only required for running tests coverage
